# Use Node.js 14 as the base image
FROM node:16-alpine AS deps

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Expose port 3000
EXPOSE 3000

# Set the command to start the application
CMD "npm" "run" "dev"

